/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KvkkAydinlatmaRouteImport } from './routes/kvkk-aydinlatma'
import { Route as UyelikSozlesmesiRouteImport } from './routes/uyelik-sozlesmesi'
import { Route as AuthenticatedAbonelikRouteImport } from './routes/_authenticated/abonelik'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAyarlarRouteImport } from './routes/_authenticated/ayarlar'
import { Route as AuthenticatedCarilerRouteImport } from './routes/_authenticated/cariler'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFaturaKesRouteImport } from './routes/_authenticated/fatura-kes'
import { Route as AuthenticatedFaturalarRouteImport } from './routes/_authenticated/faturalar'
import { Route as AuthenticatedGuncellemelerRouteImport } from './routes/_authenticated/guncellemeler'
import { Route as AuthenticatedPosSatislarRouteImport } from './routes/_authenticated/pos-satislar'
import { Route as AuthenticatedStokRouteImport } from './routes/_authenticated/stok'
import { Route as AuthenticatedUrunlerRouteImport } from './routes/_authenticated/urunler'
import { Route as AuthenticatedZRaporuRouteImport } from './routes/_authenticated/z-raporu'
import { Route as ApiPublicSubscriptionRemindersRouteImport } from './routes/api/public/subscription-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkAydinlatmaRoute = KvkkAydinlatmaRouteImport.update({
  id: '/kvkk-aydinlatma',
  path: '/kvkk-aydinlatma',
  getParentRoute: () => rootRouteImport,
} as any)
const UyelikSozlesmesiRoute = UyelikSozlesmesiRouteImport.update({
  id: '/uyelik-sozlesmesi',
  path: '/uyelik-sozlesmesi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAbonelikRoute = AuthenticatedAbonelikRouteImport.update({
  id: '/abonelik',
  path: '/abonelik',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAyarlarRoute = AuthenticatedAyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarilerRoute = AuthenticatedCarilerRouteImport.update({
  id: '/cariler',
  path: '/cariler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaturaKesRoute = AuthenticatedFaturaKesRouteImport.update({
  id: '/fatura-kes',
  path: '/fatura-kes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaturalarRoute = AuthenticatedFaturalarRouteImport.update({
  id: '/faturalar',
  path: '/faturalar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuncellemelerRoute =
  AuthenticatedGuncellemelerRouteImport.update({
    id: '/guncellemeler',
    path: '/guncellemeler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPosSatislarRoute =
  AuthenticatedPosSatislarRouteImport.update({
    id: '/pos-satislar',
    path: '/pos-satislar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStokRoute = AuthenticatedStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUrunlerRoute = AuthenticatedUrunlerRouteImport.update({
  id: '/urunler',
  path: '/urunler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZRaporuRoute = AuthenticatedZRaporuRouteImport.update({
  id: '/z-raporu',
  path: '/z-raporu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSubscriptionRemindersRoute =
  ApiPublicSubscriptionRemindersRouteImport.update({
    id: '/api/public/subscription-reminders',
    path: '/api/public/subscription-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kvkk-aydinlatma': typeof KvkkAydinlatmaRoute
  '/uyelik-sozlesmesi': typeof UyelikSozlesmesiRoute
  '/abonelik': typeof AuthenticatedAbonelikRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ayarlar': typeof AuthenticatedAyarlarRoute
  '/cariler': typeof AuthenticatedCarilerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fatura-kes': typeof AuthenticatedFaturaKesRoute
  '/faturalar': typeof AuthenticatedFaturalarRoute
  '/guncellemeler': typeof AuthenticatedGuncellemelerRoute
  '/pos-satislar': typeof AuthenticatedPosSatislarRoute
  '/stok': typeof AuthenticatedStokRoute
  '/urunler': typeof AuthenticatedUrunlerRoute
  '/z-raporu': typeof AuthenticatedZRaporuRoute
  '/api/public/subscription-reminders': typeof ApiPublicSubscriptionRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kvkk-aydinlatma': typeof KvkkAydinlatmaRoute
  '/uyelik-sozlesmesi': typeof UyelikSozlesmesiRoute
  '/abonelik': typeof AuthenticatedAbonelikRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ayarlar': typeof AuthenticatedAyarlarRoute
  '/cariler': typeof AuthenticatedCarilerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fatura-kes': typeof AuthenticatedFaturaKesRoute
  '/faturalar': typeof AuthenticatedFaturalarRoute
  '/guncellemeler': typeof AuthenticatedGuncellemelerRoute
  '/pos-satislar': typeof AuthenticatedPosSatislarRoute
  '/stok': typeof AuthenticatedStokRoute
  '/urunler': typeof AuthenticatedUrunlerRoute
  '/z-raporu': typeof AuthenticatedZRaporuRoute
  '/api/public/subscription-reminders': typeof ApiPublicSubscriptionRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kvkk-aydinlatma': typeof KvkkAydinlatmaRoute
  '/uyelik-sozlesmesi': typeof UyelikSozlesmesiRoute
  '/_authenticated/abonelik': typeof AuthenticatedAbonelikRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ayarlar': typeof AuthenticatedAyarlarRoute
  '/_authenticated/cariler': typeof AuthenticatedCarilerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fatura-kes': typeof AuthenticatedFaturaKesRoute
  '/_authenticated/faturalar': typeof AuthenticatedFaturalarRoute
  '/_authenticated/guncellemeler': typeof AuthenticatedGuncellemelerRoute
  '/_authenticated/pos-satislar': typeof AuthenticatedPosSatislarRoute
  '/_authenticated/stok': typeof AuthenticatedStokRoute
  '/_authenticated/urunler': typeof AuthenticatedUrunlerRoute
  '/_authenticated/z-raporu': typeof AuthenticatedZRaporuRoute
  '/api/public/subscription-reminders': typeof ApiPublicSubscriptionRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kvkk-aydinlatma'
    | '/uyelik-sozlesmesi'
    | '/abonelik'
    | '/admin'
    | '/ayarlar'
    | '/cariler'
    | '/dashboard'
    | '/fatura-kes'
    | '/faturalar'
    | '/guncellemeler'
    | '/pos-satislar'
    | '/stok'
    | '/urunler'
    | '/z-raporu'
    | '/api/public/subscription-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kvkk-aydinlatma'
    | '/uyelik-sozlesmesi'
    | '/abonelik'
    | '/admin'
    | '/ayarlar'
    | '/cariler'
    | '/dashboard'
    | '/fatura-kes'
    | '/faturalar'
    | '/guncellemeler'
    | '/pos-satislar'
    | '/stok'
    | '/urunler'
    | '/z-raporu'
    | '/api/public/subscription-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/kvkk-aydinlatma'
    | '/uyelik-sozlesmesi'
    | '/_authenticated/abonelik'
    | '/_authenticated/admin'
    | '/_authenticated/ayarlar'
    | '/_authenticated/cariler'
    | '/_authenticated/dashboard'
    | '/_authenticated/fatura-kes'
    | '/_authenticated/faturalar'
    | '/_authenticated/guncellemeler'
    | '/_authenticated/pos-satislar'
    | '/_authenticated/stok'
    | '/_authenticated/urunler'
    | '/_authenticated/z-raporu'
    | '/api/public/subscription-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KvkkAydinlatmaRoute: typeof KvkkAydinlatmaRoute
  UyelikSozlesmesiRoute: typeof UyelikSozlesmesiRoute
  ApiPublicSubscriptionRemindersRoute: typeof ApiPublicSubscriptionRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk-aydinlatma': {
      id: '/kvkk-aydinlatma'
      path: '/kvkk-aydinlatma'
      fullPath: '/kvkk-aydinlatma'
      preLoaderRoute: typeof KvkkAydinlatmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uyelik-sozlesmesi': {
      id: '/uyelik-sozlesmesi'
      path: '/uyelik-sozlesmesi'
      fullPath: '/uyelik-sozlesmesi'
      preLoaderRoute: typeof UyelikSozlesmesiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/abonelik': {
      id: '/_authenticated/abonelik'
      path: '/abonelik'
      fullPath: '/abonelik'
      preLoaderRoute: typeof AuthenticatedAbonelikRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ayarlar': {
      id: '/_authenticated/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AuthenticatedAyarlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cariler': {
      id: '/_authenticated/cariler'
      path: '/cariler'
      fullPath: '/cariler'
      preLoaderRoute: typeof AuthenticatedCarilerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fatura-kes': {
      id: '/_authenticated/fatura-kes'
      path: '/fatura-kes'
      fullPath: '/fatura-kes'
      preLoaderRoute: typeof AuthenticatedFaturaKesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faturalar': {
      id: '/_authenticated/faturalar'
      path: '/faturalar'
      fullPath: '/faturalar'
      preLoaderRoute: typeof AuthenticatedFaturalarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guncellemeler': {
      id: '/_authenticated/guncellemeler'
      path: '/guncellemeler'
      fullPath: '/guncellemeler'
      preLoaderRoute: typeof AuthenticatedGuncellemelerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos-satislar': {
      id: '/_authenticated/pos-satislar'
      path: '/pos-satislar'
      fullPath: '/pos-satislar'
      preLoaderRoute: typeof AuthenticatedPosSatislarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stok': {
      id: '/_authenticated/stok'
      path: '/stok'
      fullPath: '/stok'
      preLoaderRoute: typeof AuthenticatedStokRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/urunler': {
      id: '/_authenticated/urunler'
      path: '/urunler'
      fullPath: '/urunler'
      preLoaderRoute: typeof AuthenticatedUrunlerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/z-raporu': {
      id: '/_authenticated/z-raporu'
      path: '/z-raporu'
      fullPath: '/z-raporu'
      preLoaderRoute: typeof AuthenticatedZRaporuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/subscription-reminders': {
      id: '/api/public/subscription-reminders'
      path: '/api/public/subscription-reminders'
      fullPath: '/api/public/subscription-reminders'
      preLoaderRoute: typeof ApiPublicSubscriptionRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbonelikRoute: typeof AuthenticatedAbonelikRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAyarlarRoute: typeof AuthenticatedAyarlarRoute
  AuthenticatedCarilerRoute: typeof AuthenticatedCarilerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFaturaKesRoute: typeof AuthenticatedFaturaKesRoute
  AuthenticatedFaturalarRoute: typeof AuthenticatedFaturalarRoute
  AuthenticatedGuncellemelerRoute: typeof AuthenticatedGuncellemelerRoute
  AuthenticatedPosSatislarRoute: typeof AuthenticatedPosSatislarRoute
  AuthenticatedStokRoute: typeof AuthenticatedStokRoute
  AuthenticatedUrunlerRoute: typeof AuthenticatedUrunlerRoute
  AuthenticatedZRaporuRoute: typeof AuthenticatedZRaporuRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbonelikRoute: AuthenticatedAbonelikRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAyarlarRoute: AuthenticatedAyarlarRoute,
  AuthenticatedCarilerRoute: AuthenticatedCarilerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFaturaKesRoute: AuthenticatedFaturaKesRoute,
  AuthenticatedFaturalarRoute: AuthenticatedFaturalarRoute,
  AuthenticatedGuncellemelerRoute: AuthenticatedGuncellemelerRoute,
  AuthenticatedPosSatislarRoute: AuthenticatedPosSatislarRoute,
  AuthenticatedStokRoute: AuthenticatedStokRoute,
  AuthenticatedUrunlerRoute: AuthenticatedUrunlerRoute,
  AuthenticatedZRaporuRoute: AuthenticatedZRaporuRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KvkkAydinlatmaRoute: KvkkAydinlatmaRoute,
  UyelikSozlesmesiRoute: UyelikSozlesmesiRoute,
  ApiPublicSubscriptionRemindersRoute: ApiPublicSubscriptionRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
