/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KvkkAydinlatmaRouteImport } from './routes/kvkk-aydinlatma'
import { Route as UyelikSozlesmesiRouteImport } from './routes/uyelik-sozlesmesi'
import { Route as AuthenticatedAbonelikRouteImport } from './routes/_authenticated/abonelik'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAlisFaturalariRouteImport } from './routes/_authenticated/alis-faturalari'
import { Route as AuthenticatedAyarlarRouteImport } from './routes/_authenticated/ayarlar'
import { Route as AuthenticatedBankaRouteImport } from './routes/_authenticated/banka'
import { Route as AuthenticatedCarilerRouteImport } from './routes/_authenticated/cariler'
import { Route as AuthenticatedCopKutusuRouteImport } from './routes/_authenticated/cop-kutusu'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFaturaKesRouteImport } from './routes/_authenticated/fatura-kes'
import { Route as AuthenticatedFaturalarRouteImport } from './routes/_authenticated/faturalar'
import { Route as AuthenticatedGuncellemelerRouteImport } from './routes/_authenticated/guncellemeler'
import { Route as AuthenticatedKasaRouteImport } from './routes/_authenticated/kasa'
import { Route as AuthenticatedMuhasebeRouteImport } from './routes/_authenticated/muhasebe'
import { Route as AuthenticatedOdemeRouteImport } from './routes/_authenticated/odeme'
import { Route as AuthenticatedPosSatislarRouteImport } from './routes/_authenticated/pos-satislar'
import { Route as AuthenticatedRaporlarRouteImport } from './routes/_authenticated/raporlar'
import { Route as AuthenticatedSatisFaturalariRouteImport } from './routes/_authenticated/satis-faturalari'
import { Route as AuthenticatedStokRouteImport } from './routes/_authenticated/stok'
import { Route as AuthenticatedTahsilatRouteImport } from './routes/_authenticated/tahsilat'
import { Route as AuthenticatedUrunlerRouteImport } from './routes/_authenticated/urunler'
import { Route as AuthenticatedVadeTakipRouteImport } from './routes/_authenticated/vade-takip'
import { Route as AuthenticatedZRaporuRouteImport } from './routes/_authenticated/z-raporu'
import { Route as ApiInvoicesRouteImport } from './routes/api/invoices'
import { Route as AuthenticatedFaturalarIndexRouteImport } from './routes/_authenticated/faturalar/index'
import { Route as AuthenticatedFaturalarIdRouteImport } from './routes/_authenticated/faturalar/$id'
import { Route as AuthenticatedFaturalarYeniRouteImport } from './routes/_authenticated/faturalar/yeni'
import { Route as ApiEdmInvoiceRouteImport } from './routes/api/edm/invoice'
import { Route as ApiEdmPreflightRouteImport } from './routes/api/edm/preflight'
import { Route as ApiEdmTaxpayerRouteImport } from './routes/api/edm/taxpayer'
import { Route as ApiEdmTestRouteImport } from './routes/api/edm/test'
import { Route as ApiInvoicesIdRouteImport } from './routes/api/invoices/$id'
import { Route as ApiInvoicesDraftRouteImport } from './routes/api/invoices/draft'
import { Route as ApiInvoicesSummaryRouteImport } from './routes/api/invoices/summary'
import { Route as ApiInvoicesSyncRouteImport } from './routes/api/invoices/sync'
import { Route as ApiPublicSubscriptionRemindersRouteImport } from './routes/api/public/subscription-reminders'
import { Route as ApiEdmInvoiceCancelRouteImport } from './routes/api/edm/invoice.cancel'
import { Route as ApiInvoicesIdStatusRouteImport } from './routes/api/invoices/$id.status'
import { Route as ApiInvoicesIdXmlRouteImport } from './routes/api/invoices/$id.xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkAydinlatmaRoute = KvkkAydinlatmaRouteImport.update({
  id: '/kvkk-aydinlatma',
  path: '/kvkk-aydinlatma',
  getParentRoute: () => rootRouteImport,
} as any)
const UyelikSozlesmesiRoute = UyelikSozlesmesiRouteImport.update({
  id: '/uyelik-sozlesmesi',
  path: '/uyelik-sozlesmesi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAbonelikRoute = AuthenticatedAbonelikRouteImport.update({
  id: '/abonelik',
  path: '/abonelik',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlisFaturalariRoute =
  AuthenticatedAlisFaturalariRouteImport.update({
    id: '/alis-faturalari',
    path: '/alis-faturalari',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAyarlarRoute = AuthenticatedAyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankaRoute = AuthenticatedBankaRouteImport.update({
  id: '/banka',
  path: '/banka',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarilerRoute = AuthenticatedCarilerRouteImport.update({
  id: '/cariler',
  path: '/cariler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopKutusuRoute = AuthenticatedCopKutusuRouteImport.update({
  id: '/cop-kutusu',
  path: '/cop-kutusu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaturaKesRoute = AuthenticatedFaturaKesRouteImport.update({
  id: '/fatura-kes',
  path: '/fatura-kes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaturalarRoute = AuthenticatedFaturalarRouteImport.update({
  id: '/faturalar',
  path: '/faturalar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuncellemelerRoute =
  AuthenticatedGuncellemelerRouteImport.update({
    id: '/guncellemeler',
    path: '/guncellemeler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKasaRoute = AuthenticatedKasaRouteImport.update({
  id: '/kasa',
  path: '/kasa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMuhasebeRoute = AuthenticatedMuhasebeRouteImport.update({
  id: '/muhasebe',
  path: '/muhasebe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOdemeRoute = AuthenticatedOdemeRouteImport.update({
  id: '/odeme',
  path: '/odeme',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosSatislarRoute =
  AuthenticatedPosSatislarRouteImport.update({
    id: '/pos-satislar',
    path: '/pos-satislar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRaporlarRoute = AuthenticatedRaporlarRouteImport.update({
  id: '/raporlar',
  path: '/raporlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSatisFaturalariRoute =
  AuthenticatedSatisFaturalariRouteImport.update({
    id: '/satis-faturalari',
    path: '/satis-faturalari',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStokRoute = AuthenticatedStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTahsilatRoute = AuthenticatedTahsilatRouteImport.update({
  id: '/tahsilat',
  path: '/tahsilat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUrunlerRoute = AuthenticatedUrunlerRouteImport.update({
  id: '/urunler',
  path: '/urunler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVadeTakipRoute = AuthenticatedVadeTakipRouteImport.update({
  id: '/vade-takip',
  path: '/vade-takip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZRaporuRoute = AuthenticatedZRaporuRouteImport.update({
  id: '/z-raporu',
  path: '/z-raporu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiInvoicesRoute = ApiInvoicesRouteImport.update({
  id: '/api/invoices',
  path: '/api/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFaturalarIndexRoute =
  AuthenticatedFaturalarIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFaturalarRoute,
  } as any)
const AuthenticatedFaturalarIdRoute =
  AuthenticatedFaturalarIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFaturalarRoute,
  } as any)
const AuthenticatedFaturalarYeniRoute =
  AuthenticatedFaturalarYeniRouteImport.update({
    id: '/yeni',
    path: '/yeni',
    getParentRoute: () => AuthenticatedFaturalarRoute,
  } as any)
const ApiEdmInvoiceRoute = ApiEdmInvoiceRouteImport.update({
  id: '/api/edm/invoice',
  path: '/api/edm/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdmPreflightRoute = ApiEdmPreflightRouteImport.update({
  id: '/api/edm/preflight',
  path: '/api/edm/preflight',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdmTaxpayerRoute = ApiEdmTaxpayerRouteImport.update({
  id: '/api/edm/taxpayer',
  path: '/api/edm/taxpayer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdmTestRoute = ApiEdmTestRouteImport.update({
  id: '/api/edm/test',
  path: '/api/edm/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesIdRoute = ApiInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInvoicesRoute,
} as any)
const ApiInvoicesDraftRoute = ApiInvoicesDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => ApiInvoicesRoute,
} as any)
const ApiInvoicesSummaryRoute = ApiInvoicesSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ApiInvoicesRoute,
} as any)
const ApiInvoicesSyncRoute = ApiInvoicesSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => ApiInvoicesRoute,
} as any)
const ApiPublicSubscriptionRemindersRoute =
  ApiPublicSubscriptionRemindersRouteImport.update({
    id: '/api/public/subscription-reminders',
    path: '/api/public/subscription-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEdmInvoiceCancelRoute = ApiEdmInvoiceCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => ApiEdmInvoiceRoute,
} as any)
const ApiInvoicesIdStatusRoute = ApiInvoicesIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiInvoicesIdRoute,
} as any)
const ApiInvoicesIdXmlRoute = ApiInvoicesIdXmlRouteImport.update({
  id: '/xml',
  path: '/xml',
  getParentRoute: () => ApiInvoicesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kvkk-aydinlatma': typeof KvkkAydinlatmaRoute
  '/uyelik-sozlesmesi': typeof UyelikSozlesmesiRoute
  '/abonelik': typeof AuthenticatedAbonelikRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alis-faturalari': typeof AuthenticatedAlisFaturalariRoute
  '/ayarlar': typeof AuthenticatedAyarlarRoute
  '/banka': typeof AuthenticatedBankaRoute
  '/cariler': typeof AuthenticatedCarilerRoute
  '/cop-kutusu': typeof AuthenticatedCopKutusuRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fatura-kes': typeof AuthenticatedFaturaKesRoute
  '/faturalar': typeof AuthenticatedFaturalarRouteWithChildren
  '/guncellemeler': typeof AuthenticatedGuncellemelerRoute
  '/kasa': typeof AuthenticatedKasaRoute
  '/muhasebe': typeof AuthenticatedMuhasebeRoute
  '/odeme': typeof AuthenticatedOdemeRoute
  '/pos-satislar': typeof AuthenticatedPosSatislarRoute
  '/raporlar': typeof AuthenticatedRaporlarRoute
  '/satis-faturalari': typeof AuthenticatedSatisFaturalariRoute
  '/stok': typeof AuthenticatedStokRoute
  '/tahsilat': typeof AuthenticatedTahsilatRoute
  '/urunler': typeof AuthenticatedUrunlerRoute
  '/vade-takip': typeof AuthenticatedVadeTakipRoute
  '/z-raporu': typeof AuthenticatedZRaporuRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/faturalar/$id': typeof AuthenticatedFaturalarIdRoute
  '/faturalar/yeni': typeof AuthenticatedFaturalarYeniRoute
  '/api/edm/invoice': typeof ApiEdmInvoiceRouteWithChildren
  '/api/edm/preflight': typeof ApiEdmPreflightRoute
  '/api/edm/taxpayer': typeof ApiEdmTaxpayerRoute
  '/api/edm/test': typeof ApiEdmTestRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRouteWithChildren
  '/api/invoices/draft': typeof ApiInvoicesDraftRoute
  '/api/invoices/summary': typeof ApiInvoicesSummaryRoute
  '/api/invoices/sync': typeof ApiInvoicesSyncRoute
  '/api/public/subscription-reminders': typeof ApiPublicSubscriptionRemindersRoute
  '/faturalar/': typeof AuthenticatedFaturalarIndexRoute
  '/api/edm/invoice/cancel': typeof ApiEdmInvoiceCancelRoute
  '/api/invoices/$id/status': typeof ApiInvoicesIdStatusRoute
  '/api/invoices/$id/xml': typeof ApiInvoicesIdXmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kvkk-aydinlatma': typeof KvkkAydinlatmaRoute
  '/uyelik-sozlesmesi': typeof UyelikSozlesmesiRoute
  '/abonelik': typeof AuthenticatedAbonelikRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alis-faturalari': typeof AuthenticatedAlisFaturalariRoute
  '/ayarlar': typeof AuthenticatedAyarlarRoute
  '/banka': typeof AuthenticatedBankaRoute
  '/cariler': typeof AuthenticatedCarilerRoute
  '/cop-kutusu': typeof AuthenticatedCopKutusuRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fatura-kes': typeof AuthenticatedFaturaKesRoute
  '/guncellemeler': typeof AuthenticatedGuncellemelerRoute
  '/kasa': typeof AuthenticatedKasaRoute
  '/muhasebe': typeof AuthenticatedMuhasebeRoute
  '/odeme': typeof AuthenticatedOdemeRoute
  '/pos-satislar': typeof AuthenticatedPosSatislarRoute
  '/raporlar': typeof AuthenticatedRaporlarRoute
  '/satis-faturalari': typeof AuthenticatedSatisFaturalariRoute
  '/stok': typeof AuthenticatedStokRoute
  '/tahsilat': typeof AuthenticatedTahsilatRoute
  '/urunler': typeof AuthenticatedUrunlerRoute
  '/vade-takip': typeof AuthenticatedVadeTakipRoute
  '/z-raporu': typeof AuthenticatedZRaporuRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/faturalar/$id': typeof AuthenticatedFaturalarIdRoute
  '/faturalar/yeni': typeof AuthenticatedFaturalarYeniRoute
  '/api/edm/invoice': typeof ApiEdmInvoiceRouteWithChildren
  '/api/edm/preflight': typeof ApiEdmPreflightRoute
  '/api/edm/taxpayer': typeof ApiEdmTaxpayerRoute
  '/api/edm/test': typeof ApiEdmTestRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRouteWithChildren
  '/api/invoices/draft': typeof ApiInvoicesDraftRoute
  '/api/invoices/summary': typeof ApiInvoicesSummaryRoute
  '/api/invoices/sync': typeof ApiInvoicesSyncRoute
  '/api/public/subscription-reminders': typeof ApiPublicSubscriptionRemindersRoute
  '/faturalar': typeof AuthenticatedFaturalarIndexRoute
  '/api/edm/invoice/cancel': typeof ApiEdmInvoiceCancelRoute
  '/api/invoices/$id/status': typeof ApiInvoicesIdStatusRoute
  '/api/invoices/$id/xml': typeof ApiInvoicesIdXmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kvkk-aydinlatma': typeof KvkkAydinlatmaRoute
  '/uyelik-sozlesmesi': typeof UyelikSozlesmesiRoute
  '/_authenticated/abonelik': typeof AuthenticatedAbonelikRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/alis-faturalari': typeof AuthenticatedAlisFaturalariRoute
  '/_authenticated/ayarlar': typeof AuthenticatedAyarlarRoute
  '/_authenticated/banka': typeof AuthenticatedBankaRoute
  '/_authenticated/cariler': typeof AuthenticatedCarilerRoute
  '/_authenticated/cop-kutusu': typeof AuthenticatedCopKutusuRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fatura-kes': typeof AuthenticatedFaturaKesRoute
  '/_authenticated/faturalar': typeof AuthenticatedFaturalarRouteWithChildren
  '/_authenticated/guncellemeler': typeof AuthenticatedGuncellemelerRoute
  '/_authenticated/kasa': typeof AuthenticatedKasaRoute
  '/_authenticated/muhasebe': typeof AuthenticatedMuhasebeRoute
  '/_authenticated/odeme': typeof AuthenticatedOdemeRoute
  '/_authenticated/pos-satislar': typeof AuthenticatedPosSatislarRoute
  '/_authenticated/raporlar': typeof AuthenticatedRaporlarRoute
  '/_authenticated/satis-faturalari': typeof AuthenticatedSatisFaturalariRoute
  '/_authenticated/stok': typeof AuthenticatedStokRoute
  '/_authenticated/tahsilat': typeof AuthenticatedTahsilatRoute
  '/_authenticated/urunler': typeof AuthenticatedUrunlerRoute
  '/_authenticated/vade-takip': typeof AuthenticatedVadeTakipRoute
  '/_authenticated/z-raporu': typeof AuthenticatedZRaporuRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/_authenticated/faturalar/$id': typeof AuthenticatedFaturalarIdRoute
  '/_authenticated/faturalar/yeni': typeof AuthenticatedFaturalarYeniRoute
  '/api/edm/invoice': typeof ApiEdmInvoiceRouteWithChildren
  '/api/edm/preflight': typeof ApiEdmPreflightRoute
  '/api/edm/taxpayer': typeof ApiEdmTaxpayerRoute
  '/api/edm/test': typeof ApiEdmTestRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRouteWithChildren
  '/api/invoices/draft': typeof ApiInvoicesDraftRoute
  '/api/invoices/summary': typeof ApiInvoicesSummaryRoute
  '/api/invoices/sync': typeof ApiInvoicesSyncRoute
  '/api/public/subscription-reminders': typeof ApiPublicSubscriptionRemindersRoute
  '/_authenticated/faturalar/': typeof AuthenticatedFaturalarIndexRoute
  '/api/edm/invoice/cancel': typeof ApiEdmInvoiceCancelRoute
  '/api/invoices/$id/status': typeof ApiInvoicesIdStatusRoute
  '/api/invoices/$id/xml': typeof ApiInvoicesIdXmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kvkk-aydinlatma'
    | '/uyelik-sozlesmesi'
    | '/abonelik'
    | '/admin'
    | '/alis-faturalari'
    | '/ayarlar'
    | '/banka'
    | '/cariler'
    | '/cop-kutusu'
    | '/dashboard'
    | '/fatura-kes'
    | '/faturalar'
    | '/guncellemeler'
    | '/kasa'
    | '/muhasebe'
    | '/odeme'
    | '/pos-satislar'
    | '/raporlar'
    | '/satis-faturalari'
    | '/stok'
    | '/tahsilat'
    | '/urunler'
    | '/vade-takip'
    | '/z-raporu'
    | '/api/invoices'
    | '/faturalar/$id'
    | '/faturalar/yeni'
    | '/api/edm/invoice'
    | '/api/edm/preflight'
    | '/api/edm/taxpayer'
    | '/api/edm/test'
    | '/api/invoices/$id'
    | '/api/invoices/draft'
    | '/api/invoices/summary'
    | '/api/invoices/sync'
    | '/api/public/subscription-reminders'
    | '/faturalar/'
    | '/api/edm/invoice/cancel'
    | '/api/invoices/$id/status'
    | '/api/invoices/$id/xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kvkk-aydinlatma'
    | '/uyelik-sozlesmesi'
    | '/abonelik'
    | '/admin'
    | '/alis-faturalari'
    | '/ayarlar'
    | '/banka'
    | '/cariler'
    | '/cop-kutusu'
    | '/dashboard'
    | '/fatura-kes'
    | '/guncellemeler'
    | '/kasa'
    | '/muhasebe'
    | '/odeme'
    | '/pos-satislar'
    | '/raporlar'
    | '/satis-faturalari'
    | '/stok'
    | '/tahsilat'
    | '/urunler'
    | '/vade-takip'
    | '/z-raporu'
    | '/api/invoices'
    | '/faturalar/$id'
    | '/faturalar/yeni'
    | '/api/edm/invoice'
    | '/api/edm/preflight'
    | '/api/edm/taxpayer'
    | '/api/edm/test'
    | '/api/invoices/$id'
    | '/api/invoices/draft'
    | '/api/invoices/summary'
    | '/api/invoices/sync'
    | '/api/public/subscription-reminders'
    | '/faturalar'
    | '/api/edm/invoice/cancel'
    | '/api/invoices/$id/status'
    | '/api/invoices/$id/xml'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/kvkk-aydinlatma'
    | '/uyelik-sozlesmesi'
    | '/_authenticated/abonelik'
    | '/_authenticated/admin'
    | '/_authenticated/alis-faturalari'
    | '/_authenticated/ayarlar'
    | '/_authenticated/banka'
    | '/_authenticated/cariler'
    | '/_authenticated/cop-kutusu'
    | '/_authenticated/dashboard'
    | '/_authenticated/fatura-kes'
    | '/_authenticated/faturalar'
    | '/_authenticated/guncellemeler'
    | '/_authenticated/kasa'
    | '/_authenticated/muhasebe'
    | '/_authenticated/odeme'
    | '/_authenticated/pos-satislar'
    | '/_authenticated/raporlar'
    | '/_authenticated/satis-faturalari'
    | '/_authenticated/stok'
    | '/_authenticated/tahsilat'
    | '/_authenticated/urunler'
    | '/_authenticated/vade-takip'
    | '/_authenticated/z-raporu'
    | '/api/invoices'
    | '/_authenticated/faturalar/$id'
    | '/_authenticated/faturalar/yeni'
    | '/api/edm/invoice'
    | '/api/edm/preflight'
    | '/api/edm/taxpayer'
    | '/api/edm/test'
    | '/api/invoices/$id'
    | '/api/invoices/draft'
    | '/api/invoices/summary'
    | '/api/invoices/sync'
    | '/api/public/subscription-reminders'
    | '/_authenticated/faturalar/'
    | '/api/edm/invoice/cancel'
    | '/api/invoices/$id/status'
    | '/api/invoices/$id/xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KvkkAydinlatmaRoute: typeof KvkkAydinlatmaRoute
  UyelikSozlesmesiRoute: typeof UyelikSozlesmesiRoute
  ApiInvoicesRoute: typeof ApiInvoicesRouteWithChildren
  ApiEdmInvoiceRoute: typeof ApiEdmInvoiceRouteWithChildren
  ApiEdmPreflightRoute: typeof ApiEdmPreflightRoute
  ApiEdmTaxpayerRoute: typeof ApiEdmTaxpayerRoute
  ApiEdmTestRoute: typeof ApiEdmTestRoute
  ApiPublicSubscriptionRemindersRoute: typeof ApiPublicSubscriptionRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk-aydinlatma': {
      id: '/kvkk-aydinlatma'
      path: '/kvkk-aydinlatma'
      fullPath: '/kvkk-aydinlatma'
      preLoaderRoute: typeof KvkkAydinlatmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uyelik-sozlesmesi': {
      id: '/uyelik-sozlesmesi'
      path: '/uyelik-sozlesmesi'
      fullPath: '/uyelik-sozlesmesi'
      preLoaderRoute: typeof UyelikSozlesmesiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/abonelik': {
      id: '/_authenticated/abonelik'
      path: '/abonelik'
      fullPath: '/abonelik'
      preLoaderRoute: typeof AuthenticatedAbonelikRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alis-faturalari': {
      id: '/_authenticated/alis-faturalari'
      path: '/alis-faturalari'
      fullPath: '/alis-faturalari'
      preLoaderRoute: typeof AuthenticatedAlisFaturalariRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ayarlar': {
      id: '/_authenticated/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AuthenticatedAyarlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banka': {
      id: '/_authenticated/banka'
      path: '/banka'
      fullPath: '/banka'
      preLoaderRoute: typeof AuthenticatedBankaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cariler': {
      id: '/_authenticated/cariler'
      path: '/cariler'
      fullPath: '/cariler'
      preLoaderRoute: typeof AuthenticatedCarilerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cop-kutusu': {
      id: '/_authenticated/cop-kutusu'
      path: '/cop-kutusu'
      fullPath: '/cop-kutusu'
      preLoaderRoute: typeof AuthenticatedCopKutusuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fatura-kes': {
      id: '/_authenticated/fatura-kes'
      path: '/fatura-kes'
      fullPath: '/fatura-kes'
      preLoaderRoute: typeof AuthenticatedFaturaKesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faturalar': {
      id: '/_authenticated/faturalar'
      path: '/faturalar'
      fullPath: '/faturalar'
      preLoaderRoute: typeof AuthenticatedFaturalarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guncellemeler': {
      id: '/_authenticated/guncellemeler'
      path: '/guncellemeler'
      fullPath: '/guncellemeler'
      preLoaderRoute: typeof AuthenticatedGuncellemelerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kasa': {
      id: '/_authenticated/kasa'
      path: '/kasa'
      fullPath: '/kasa'
      preLoaderRoute: typeof AuthenticatedKasaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/muhasebe': {
      id: '/_authenticated/muhasebe'
      path: '/muhasebe'
      fullPath: '/muhasebe'
      preLoaderRoute: typeof AuthenticatedMuhasebeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/odeme': {
      id: '/_authenticated/odeme'
      path: '/odeme'
      fullPath: '/odeme'
      preLoaderRoute: typeof AuthenticatedOdemeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos-satislar': {
      id: '/_authenticated/pos-satislar'
      path: '/pos-satislar'
      fullPath: '/pos-satislar'
      preLoaderRoute: typeof AuthenticatedPosSatislarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/raporlar': {
      id: '/_authenticated/raporlar'
      path: '/raporlar'
      fullPath: '/raporlar'
      preLoaderRoute: typeof AuthenticatedRaporlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/satis-faturalari': {
      id: '/_authenticated/satis-faturalari'
      path: '/satis-faturalari'
      fullPath: '/satis-faturalari'
      preLoaderRoute: typeof AuthenticatedSatisFaturalariRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stok': {
      id: '/_authenticated/stok'
      path: '/stok'
      fullPath: '/stok'
      preLoaderRoute: typeof AuthenticatedStokRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tahsilat': {
      id: '/_authenticated/tahsilat'
      path: '/tahsilat'
      fullPath: '/tahsilat'
      preLoaderRoute: typeof AuthenticatedTahsilatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/urunler': {
      id: '/_authenticated/urunler'
      path: '/urunler'
      fullPath: '/urunler'
      preLoaderRoute: typeof AuthenticatedUrunlerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vade-takip': {
      id: '/_authenticated/vade-takip'
      path: '/vade-takip'
      fullPath: '/vade-takip'
      preLoaderRoute: typeof AuthenticatedVadeTakipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/z-raporu': {
      id: '/_authenticated/z-raporu'
      path: '/z-raporu'
      fullPath: '/z-raporu'
      preLoaderRoute: typeof AuthenticatedZRaporuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/invoices': {
      id: '/api/invoices'
      path: '/api/invoices'
      fullPath: '/api/invoices'
      preLoaderRoute: typeof ApiInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/faturalar/': {
      id: '/_authenticated/faturalar/'
      path: '/'
      fullPath: '/faturalar/'
      preLoaderRoute: typeof AuthenticatedFaturalarIndexRouteImport
      parentRoute: typeof AuthenticatedFaturalarRoute
    }
    '/_authenticated/faturalar/$id': {
      id: '/_authenticated/faturalar/$id'
      path: '/$id'
      fullPath: '/faturalar/$id'
      preLoaderRoute: typeof AuthenticatedFaturalarIdRouteImport
      parentRoute: typeof AuthenticatedFaturalarRoute
    }
    '/_authenticated/faturalar/yeni': {
      id: '/_authenticated/faturalar/yeni'
      path: '/yeni'
      fullPath: '/faturalar/yeni'
      preLoaderRoute: typeof AuthenticatedFaturalarYeniRouteImport
      parentRoute: typeof AuthenticatedFaturalarRoute
    }
    '/api/edm/invoice': {
      id: '/api/edm/invoice'
      path: '/api/edm/invoice'
      fullPath: '/api/edm/invoice'
      preLoaderRoute: typeof ApiEdmInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edm/preflight': {
      id: '/api/edm/preflight'
      path: '/api/edm/preflight'
      fullPath: '/api/edm/preflight'
      preLoaderRoute: typeof ApiEdmPreflightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edm/taxpayer': {
      id: '/api/edm/taxpayer'
      path: '/api/edm/taxpayer'
      fullPath: '/api/edm/taxpayer'
      preLoaderRoute: typeof ApiEdmTaxpayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edm/test': {
      id: '/api/edm/test'
      path: '/api/edm/test'
      fullPath: '/api/edm/test'
      preLoaderRoute: typeof ApiEdmTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices/$id': {
      id: '/api/invoices/$id'
      path: '/$id'
      fullPath: '/api/invoices/$id'
      preLoaderRoute: typeof ApiInvoicesIdRouteImport
      parentRoute: typeof ApiInvoicesRoute
    }
    '/api/invoices/draft': {
      id: '/api/invoices/draft'
      path: '/draft'
      fullPath: '/api/invoices/draft'
      preLoaderRoute: typeof ApiInvoicesDraftRouteImport
      parentRoute: typeof ApiInvoicesRoute
    }
    '/api/invoices/summary': {
      id: '/api/invoices/summary'
      path: '/summary'
      fullPath: '/api/invoices/summary'
      preLoaderRoute: typeof ApiInvoicesSummaryRouteImport
      parentRoute: typeof ApiInvoicesRoute
    }
    '/api/invoices/sync': {
      id: '/api/invoices/sync'
      path: '/sync'
      fullPath: '/api/invoices/sync'
      preLoaderRoute: typeof ApiInvoicesSyncRouteImport
      parentRoute: typeof ApiInvoicesRoute
    }
    '/api/public/subscription-reminders': {
      id: '/api/public/subscription-reminders'
      path: '/api/public/subscription-reminders'
      fullPath: '/api/public/subscription-reminders'
      preLoaderRoute: typeof ApiPublicSubscriptionRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edm/invoice/cancel': {
      id: '/api/edm/invoice/cancel'
      path: '/cancel'
      fullPath: '/api/edm/invoice/cancel'
      preLoaderRoute: typeof ApiEdmInvoiceCancelRouteImport
      parentRoute: typeof ApiEdmInvoiceRoute
    }
    '/api/invoices/$id/status': {
      id: '/api/invoices/$id/status'
      path: '/status'
      fullPath: '/api/invoices/$id/status'
      preLoaderRoute: typeof ApiInvoicesIdStatusRouteImport
      parentRoute: typeof ApiInvoicesIdRoute
    }
    '/api/invoices/$id/xml': {
      id: '/api/invoices/$id/xml'
      path: '/xml'
      fullPath: '/api/invoices/$id/xml'
      preLoaderRoute: typeof ApiInvoicesIdXmlRouteImport
      parentRoute: typeof ApiInvoicesIdRoute
    }
  }
}

interface AuthenticatedFaturalarRouteChildren {
  AuthenticatedFaturalarIdRoute: typeof AuthenticatedFaturalarIdRoute
  AuthenticatedFaturalarYeniRoute: typeof AuthenticatedFaturalarYeniRoute
  AuthenticatedFaturalarIndexRoute: typeof AuthenticatedFaturalarIndexRoute
}

const AuthenticatedFaturalarRouteChildren: AuthenticatedFaturalarRouteChildren =
  {
    AuthenticatedFaturalarIdRoute: AuthenticatedFaturalarIdRoute,
    AuthenticatedFaturalarYeniRoute: AuthenticatedFaturalarYeniRoute,
    AuthenticatedFaturalarIndexRoute: AuthenticatedFaturalarIndexRoute,
  }

const AuthenticatedFaturalarRouteWithChildren =
  AuthenticatedFaturalarRoute._addFileChildren(
    AuthenticatedFaturalarRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbonelikRoute: typeof AuthenticatedAbonelikRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlisFaturalariRoute: typeof AuthenticatedAlisFaturalariRoute
  AuthenticatedAyarlarRoute: typeof AuthenticatedAyarlarRoute
  AuthenticatedBankaRoute: typeof AuthenticatedBankaRoute
  AuthenticatedCarilerRoute: typeof AuthenticatedCarilerRoute
  AuthenticatedCopKutusuRoute: typeof AuthenticatedCopKutusuRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFaturaKesRoute: typeof AuthenticatedFaturaKesRoute
  AuthenticatedFaturalarRoute: typeof AuthenticatedFaturalarRouteWithChildren
  AuthenticatedGuncellemelerRoute: typeof AuthenticatedGuncellemelerRoute
  AuthenticatedKasaRoute: typeof AuthenticatedKasaRoute
  AuthenticatedMuhasebeRoute: typeof AuthenticatedMuhasebeRoute
  AuthenticatedOdemeRoute: typeof AuthenticatedOdemeRoute
  AuthenticatedPosSatislarRoute: typeof AuthenticatedPosSatislarRoute
  AuthenticatedRaporlarRoute: typeof AuthenticatedRaporlarRoute
  AuthenticatedSatisFaturalariRoute: typeof AuthenticatedSatisFaturalariRoute
  AuthenticatedStokRoute: typeof AuthenticatedStokRoute
  AuthenticatedTahsilatRoute: typeof AuthenticatedTahsilatRoute
  AuthenticatedUrunlerRoute: typeof AuthenticatedUrunlerRoute
  AuthenticatedVadeTakipRoute: typeof AuthenticatedVadeTakipRoute
  AuthenticatedZRaporuRoute: typeof AuthenticatedZRaporuRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbonelikRoute: AuthenticatedAbonelikRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlisFaturalariRoute: AuthenticatedAlisFaturalariRoute,
  AuthenticatedAyarlarRoute: AuthenticatedAyarlarRoute,
  AuthenticatedBankaRoute: AuthenticatedBankaRoute,
  AuthenticatedCarilerRoute: AuthenticatedCarilerRoute,
  AuthenticatedCopKutusuRoute: AuthenticatedCopKutusuRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFaturaKesRoute: AuthenticatedFaturaKesRoute,
  AuthenticatedFaturalarRoute: AuthenticatedFaturalarRouteWithChildren,
  AuthenticatedGuncellemelerRoute: AuthenticatedGuncellemelerRoute,
  AuthenticatedKasaRoute: AuthenticatedKasaRoute,
  AuthenticatedMuhasebeRoute: AuthenticatedMuhasebeRoute,
  AuthenticatedOdemeRoute: AuthenticatedOdemeRoute,
  AuthenticatedPosSatislarRoute: AuthenticatedPosSatislarRoute,
  AuthenticatedRaporlarRoute: AuthenticatedRaporlarRoute,
  AuthenticatedSatisFaturalariRoute: AuthenticatedSatisFaturalariRoute,
  AuthenticatedStokRoute: AuthenticatedStokRoute,
  AuthenticatedTahsilatRoute: AuthenticatedTahsilatRoute,
  AuthenticatedUrunlerRoute: AuthenticatedUrunlerRoute,
  AuthenticatedVadeTakipRoute: AuthenticatedVadeTakipRoute,
  AuthenticatedZRaporuRoute: AuthenticatedZRaporuRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiInvoicesIdRouteChildren {
  ApiInvoicesIdStatusRoute: typeof ApiInvoicesIdStatusRoute
  ApiInvoicesIdXmlRoute: typeof ApiInvoicesIdXmlRoute
}

const ApiInvoicesIdRouteChildren: ApiInvoicesIdRouteChildren = {
  ApiInvoicesIdStatusRoute: ApiInvoicesIdStatusRoute,
  ApiInvoicesIdXmlRoute: ApiInvoicesIdXmlRoute,
}

const ApiInvoicesIdRouteWithChildren = ApiInvoicesIdRoute._addFileChildren(
  ApiInvoicesIdRouteChildren,
)

interface ApiInvoicesRouteChildren {
  ApiInvoicesIdRoute: typeof ApiInvoicesIdRouteWithChildren
  ApiInvoicesDraftRoute: typeof ApiInvoicesDraftRoute
  ApiInvoicesSummaryRoute: typeof ApiInvoicesSummaryRoute
  ApiInvoicesSyncRoute: typeof ApiInvoicesSyncRoute
}

const ApiInvoicesRouteChildren: ApiInvoicesRouteChildren = {
  ApiInvoicesIdRoute: ApiInvoicesIdRouteWithChildren,
  ApiInvoicesDraftRoute: ApiInvoicesDraftRoute,
  ApiInvoicesSummaryRoute: ApiInvoicesSummaryRoute,
  ApiInvoicesSyncRoute: ApiInvoicesSyncRoute,
}

const ApiInvoicesRouteWithChildren = ApiInvoicesRoute._addFileChildren(
  ApiInvoicesRouteChildren,
)

interface ApiEdmInvoiceRouteChildren {
  ApiEdmInvoiceCancelRoute: typeof ApiEdmInvoiceCancelRoute
}

const ApiEdmInvoiceRouteChildren: ApiEdmInvoiceRouteChildren = {
  ApiEdmInvoiceCancelRoute: ApiEdmInvoiceCancelRoute,
}

const ApiEdmInvoiceRouteWithChildren = ApiEdmInvoiceRoute._addFileChildren(
  ApiEdmInvoiceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KvkkAydinlatmaRoute: KvkkAydinlatmaRoute,
  UyelikSozlesmesiRoute: UyelikSozlesmesiRoute,
  ApiInvoicesRoute: ApiInvoicesRouteWithChildren,
  ApiEdmInvoiceRoute: ApiEdmInvoiceRouteWithChildren,
  ApiEdmPreflightRoute: ApiEdmPreflightRoute,
  ApiEdmTaxpayerRoute: ApiEdmTaxpayerRoute,
  ApiEdmTestRoute: ApiEdmTestRoute,
  ApiPublicSubscriptionRemindersRoute: ApiPublicSubscriptionRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
